version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "expo"
      - dependency-name: "@expo/*"
      - dependency-name: "expo-router"
      - dependency-name: "react-native"
      - dependency-name: "react-native-gesture-handler"
      - dependency-name: "react-native-safe-area-context"
      - dependency-name: "react-native-screens"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
